import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

const ROOT = path.resolve(import.meta.dirname, "..");
const CLI = path.join(ROOT, "bin", "workloop.mjs");
function git(cwd, args) { return execFileSync("git", args, { cwd, encoding: "utf8" }).trim(); }
function run(args, fx, session = "receipt-session") { return spawnSync(process.execPath, [CLI, ...args], { cwd: ROOT, encoding: "utf8", timeout: 20_000, env: { ...process.env, WORKLOOP_SESSION_ID: session, WORKLOOP_AUTHORITY_HOME: fx.home } }); }
function json(result) { assert.equal(result.status, 0, result.stderr || result.stdout); return JSON.parse(result.stdout); }
function fixture(t) { const base = fs.mkdtempSync(path.join(os.tmpdir(), "workloop-git-receipt-")); const repo = path.join(base, "repo"); const home = path.join(base, "home"); fs.mkdirSync(repo); git(repo, ["init", "-q"]); git(repo, ["config", "user.name", "Receipt Test"]); git(repo, ["config", "user.email", "receipt@example.invalid"]); fs.mkdirSync(path.join(repo, "src")); fs.mkdirSync(path.join(repo, "docs")); fs.writeFileSync(path.join(repo, "src", "a.txt"), "base\n"); fs.writeFileSync(path.join(repo, "docs", "b.txt"), "base\n"); git(repo, ["add", "."]); git(repo, ["commit", "-qm", "base"]); t.after(() => fs.rmSync(base, { recursive: true, force: true })); return { base, repo, home }; }
function open(fx, root, command, session = "receipt-session") { return json(run(["open", "--target", path.join(fx.repo, root, "future.txt"), "--goal", command, "--write-root", root, "--command-id", command, "--reason", "ticket09 fixture", "--granted-by", "self"], fx, session)); }

test("task-scoped stage preserves another task index entry and commit leaves it staged", (t) => { const fx = fixture(t); const source = open(fx, "src", "open-src"); const docs = open(fx, "docs", "open-docs", "docs-session"); fs.writeFileSync(path.join(fx.repo, "src", "a.txt"), "source change\n"); fs.writeFileSync(path.join(fx.repo, "docs", "b.txt"), "docs change\n"); git(fx.repo, ["add", "docs/b.txt"]); const staged = json(run(["stage", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--command-id", "stage-src", "--reason", "stage source task", "--granted-by", "user"], fx)); assert.equal(staged.receipt.clean, false); assert.equal(staged.receipt.status, "uncertain"); assert.deepEqual(git(fx.repo, ["diff", "--cached", "--name-only"]).split("\n").sort(), ["docs/b.txt", "src/a.txt"]); const committed = json(run(["commit", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--message", "source only", "--command-id", "commit-src", "--reason", "commit source task", "--granted-by", "user"], fx)); assert.equal(committed.receipt.clean, false); assert.equal(committed.receipt.status, "uncertain"); assert.deepEqual(git(fx.repo, ["show", "--format=", "--name-only", "HEAD"]).split("\n").filter(Boolean), ["src/a.txt"]); assert.deepEqual(git(fx.repo, ["diff", "--cached", "--name-only"]).split("\n").filter(Boolean), ["docs/b.txt"]); assert.equal(docs.task.task_id.length, 36); });

test("a clean stage receipt causally binds a clean task-scoped commit", (t) => { const fx = fixture(t); const source = open(fx, "src", "open-clean"); fs.writeFileSync(path.join(fx.repo, "src", "a.txt"), "clean source change\n"); const staged = json(run(["stage", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--command-id", "stage-clean", "--reason", "stage source task", "--granted-by", "user"], fx)); assert.equal(staged.receipt.clean, true); const committed = json(run(["commit", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--message", "clean source", "--command-id", "commit-clean", "--reason", "commit source task", "--granted-by", "user"], fx)); assert.equal(committed.receipt.clean, true); assert.equal(committed.receipt.prior_head, committed.receipt.parent_oid); assert.deepEqual(committed.receipt.diff_paths, ["src/a.txt"]); });

test("a post-stage host index mutation persists an uncertain commit receipt", (t) => { const fx = fixture(t); const source = open(fx, "src", "open-post-stage"); fs.writeFileSync(path.join(fx.repo, "src", "a.txt"), "source change\n"); const staged = json(run(["stage", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--command-id", "stage-post-stage", "--reason", "stage source task", "--granted-by", "user"], fx)); assert.equal(staged.receipt.clean, true); fs.writeFileSync(path.join(fx.repo, "docs", "b.txt"), "host index mutation\n"); git(fx.repo, ["add", "docs/b.txt"]); const committed = json(run(["commit", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--message", "source only", "--command-id", "commit-post-stage", "--reason", "commit source task", "--granted-by", "user"], fx)); assert.equal(committed.receipt.clean, false); assert.equal(committed.receipt.status, "uncertain"); assert.deepEqual(git(fx.repo, ["diff", "--cached", "--name-only"]).split("\n").filter(Boolean), ["docs/b.txt"]); });

test("certify achieves a Git task only while its clean receipt remains landed", (t) => { const fx = fixture(t); const source = open(fx, "src", "open-certify"); fs.writeFileSync(path.join(fx.repo, "src", "a.txt"), "certified source change\n"); const staged = json(run(["stage", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--command-id", "stage-certify", "--reason", "stage", "--granted-by", "user"], fx)); assert.equal(staged.receipt.clean, true); const committed = json(run(["commit", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--message", "certify", "--command-id", "commit-certify", "--reason", "commit", "--granted-by", "user"], fx)); fs.writeFileSync(path.join(fx.repo, "check.mjs"), "process.exit(4);\n"); const certified = json(run(["certify", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--criterion-file", "check.mjs", "--command-id", "certify", "--reason", "criterion satisfied", "--granted-by", "self"], fx)); assert.equal(certified.task.lifecycle.outcome, "achieved"); assert.equal(certified.task.certification.commit_oid, committed.receipt.commit_oid); });

test("certify rejects a receipt whose task paths were subsequently changed", (t) => { const fx = fixture(t); const source = open(fx, "src", "open-reversed"); fs.writeFileSync(path.join(fx.repo, "src", "a.txt"), "first change\n"); json(run(["stage", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--command-id", "stage-reversed", "--reason", "stage", "--granted-by", "user"], fx)); json(run(["commit", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--message", "first", "--command-id", "commit-reversed", "--reason", "commit", "--granted-by", "user"], fx)); fs.writeFileSync(path.join(fx.repo, "src", "a.txt"), "reversed later\n"); git(fx.repo, ["add", "src/a.txt"]); git(fx.repo, ["commit", "-qm", "host later change"]); fs.writeFileSync(path.join(fx.repo, "check.mjs"), "process.exit(4);\n"); const rejected = run(["certify", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--criterion-file", "check.mjs", "--command-id", "certify-reversed", "--reason", "criterion satisfied", "--granted-by", "self"], fx); assert.equal(rejected.status, 2); assert.match(rejected.stderr, /task paths changed after the clean receipt commit/); });

test("certify rejects unstaged and staged task-path drift after a clean receipt", (t) => { const fx = fixture(t); const source = open(fx, "src", "open-worktree-drift"); fs.writeFileSync(path.join(fx.repo, "src", "a.txt"), "receipt state\n"); json(run(["stage", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--command-id", "stage-worktree-drift", "--reason", "stage", "--granted-by", "user"], fx)); json(run(["commit", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--message", "receipt", "--command-id", "commit-worktree-drift", "--reason", "commit", "--granted-by", "user"], fx)); fs.writeFileSync(path.join(fx.repo, "check.mjs"), "process.exit(4);\n"); fs.writeFileSync(path.join(fx.repo, "src", "a.txt"), "unstaged drift\n"); let rejected = run(["certify", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--criterion-file", "check.mjs", "--command-id", "certify-unstaged", "--reason", "criterion", "--granted-by", "self"], fx); assert.equal(rejected.status, 2); assert.match(rejected.stderr, /task paths changed after the clean receipt commit/); git(fx.repo, ["add", "src/a.txt"]); rejected = run(["certify", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--criterion-file", "check.mjs", "--command-id", "certify-staged", "--reason", "criterion", "--granted-by", "self"], fx); assert.equal(rejected.status, 2); assert.match(rejected.stderr, /task paths changed after the clean receipt commit/); });

test("a direct Git race keeps host success but records an uncertain receipt", (t) => { const fx = fixture(t); const source = open(fx, "src", "open-race"); fs.writeFileSync(path.join(fx.repo, "src", "a.txt"), "source change\n"); git(fx.repo, ["add", "src/a.txt"]); const raced = json(run(["stage", "--target", path.join(fx.repo, "src", "a.txt"), "--task-id", source.task.task_id, "--command-id", "stage-race", "--reason", "stage source task", "--granted-by", "user"], fx)); assert.equal(raced.receipt.clean, false); assert.equal(raced.receipt.status, "uncertain"); });
